project:
  name: quickstart-phsa-ipac
  owner: quickstart@amazon.com
  #package_lambda: true
  s3_regional_buckets: false
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - ca-central-1
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  #s3_bucket: ''
  template: templates/ipac-pipeline-entrypoint.template.yaml
tests:
  ipac-pipeline-default:
    parameters:
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      Environment: dev
      Region: $[taskcat_current_region]
      #SageMakerPrivateWorkTeamArn: arn:aws:sagemaker:ca-central-1:165536952993:workteam/private-crowd/digitalproducts-ipac
    regions:
    - us-east-1
