version: 0.0
Resources:
  - job_creation:
      Type: "AWS::Lambda::Function"
      Properties:
        Name: sagemaker-ipac-clabsi-job-creation
        Alias: live
        CurrentVersion: 1
        TargetVersion: 2
