version: 0.0
Resources:
  - feedback_loop:
      type: "AWS::Lambda::Function"
      properties:
        name: sagemaker-ipac-clabsi-production-feedback-loop
        alias: live
        currentversion: 1
        targetversion: 2