// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

=== Test the deployment
// If steps are required to test the deployment, add them here. If not, remove the heading
* Upload assets/anonymous_patients.xlsx to the input data S3 bucket to simulate the ingestion of patient data into the system. Labeling jobs should be created in GroundTruth.
* Complete a review and confirm that the job is relaunched in Ground Truth for labeling by a second reviewer.
* Submit a job with the label `Require further review - revisit patient later`. Confirm that the job launches with same number of reviewers required.
* Confirm that created jobs are recorded in the time sheet.* 

For more information, see https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_HumanTaskConfig.html#:~:text=TaskTimeLimitInSeconds[HumanTaskConfig].

=== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading
Create a private workforce in your Amazon SageMaker deployment. For more information, see https://docs.aws.amazon.com/sagemaker/latest/dg/sms-workforce-create-private-console.html[Create a Private Workforce (Amazon SageMaker Console)]. 

=== Best practices for reviewers using {partner-product-short-name} on AWS
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.
- If you are not finished reviewing a case but want to save your work and resume later, submit the job with the label `Require further review - revisit patient later`.
- Enter your reasons behind a decision in the *Comment* field.
- You can leave comments on Infection Window Period (IWP) plots (`comment_on_iwp`) and on pathogens (`comment_on_pathogen`).

=== Security
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.
* https://aws.amazon.com/architecture/security-identity-compliance/?cards-all.sort-by=item.additionalFields.sortDate&cards-all.sort-order=desc[Security Best Practices by AWS]

// == Other useful information
//Provide any other information of interest to users, especially focusing on areas where AWS or cloud usage differs from on-premises usage.

